My_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", include("main.urls")),
    path("blogs/", include("blogs.urls")),
    path("projects/", include("projects.urls")),
    path('admin/', admin.site.urls),
    path("ckeditor/", include("ckeditor_uploader.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.urls import path
from . import views


app_name = "blogs"

urlpatterns = [
    path("", views.BlogsView, name = "blogs"),
    path("<str:slug>", views.BlogView, name = "blog"),
    path("hashtag/<int:id>", views.BlogsWithHashtagView, name = "blogsWithHashtag"),
]

main/urls.py
from django.urls import path, include
from . import views

app_name = "main"
urlpatterns = [
    path("", views.HomePageView, name = "main"),
]

projects/urls.py
from django.urls import path
from . import views


app_name = "projects"

urlpatterns = [
    path("", views.ProjectsView, name = "projects"),
    path("<str:slug>", views.ProjectView, name = "project"),
    path("hashtag/<int:id>", views.ProjectsWithHashtagView, name = "projectsWithHashtag"),
]

blogs/models.py
from django.db import models
from datetime import datetime
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField


# Create your models here.
class HashtagForBlog(models.Model):
    content = models.CharField(max_length=100)

    def __str__(self):
        return str(self.id) + self.content

class Blog(models.Model):
    title = models.CharField(max_length=100)
    description = RichTextField()
    mini_description = models.CharField(max_length=300, default="")
    dateCreated = models.DateTimeField(default=datetime.now())
    imageField = models.ImageField(upload_to="blogs/blogs_pics", default="blogs/blogs_pics/default.png", null = True)
    viewsCount = models.IntegerField(default=0)
    hashtags = models.ManyToManyField(HashtagForBlog, blank = True, related_name = "posts")
    slug = models.CharField(max_length=1000, null=True, blank=True)

    def __str__(self):
        return self.title
    

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title + "-" + str(self.dateCreated))
        return super().save(*args, **kwargs)

projects/models.py
from django.db import models
from datetime import datetime
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField


# Create your models here.
class HashtagForProject(models.Model):
    content = models.CharField(max_length=100)

    def __str__(self):
        return str(self.id) + self.content

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = RichTextField()
    mini_description = models.CharField(max_length=300, default="")
    dateCreated = models.DateTimeField(default=datetime.now())
    imageField = models.ImageField(upload_to="projects/projects_pics", default="projects/projects_pics/default.png", null = True)
    viewsCount = models.IntegerField(default=0)
    hashtags = models.ManyToManyField(HashtagForProject, blank = True, related_name = "projects")
    slug = models.CharField(max_length=1000, null=True, blank=True)

    def __str__(self):
        return self.title
    

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title + "-" + str(self.dateCreated))
        return super().save(*args, **kwargs)

blogs/views.py
from django.shortcuts import render, get_object_or_404
from django.http import request
from .models import Blog, HashtagForBlog

# Create your views here.

def BlogsView(request):
    blogs = Blog.objects.order_by("-dateCreated")
    context = {
        "hashtags": HashtagForBlog.objects.all(),
        "blogs": blogs
    }
    return render(request, "blogs/blogs.html", context=context)


def BlogsWithHashtagView(request, id):
    hashtag = get_object_or_404(HashtagForBlog, pk = id)

    blogs = hashtag.posts.order_by("-dateCreated")
    context = {
        "queriedHashtag": hashtag,
        "hashtags": HashtagForBlog.objects.all(),
        "blogs": blogs
    }
    return render(request, "blogs/blogs.html", context=context)


def BlogView(request, slug):
    blog = get_object_or_404(Blog, slug=slug)
    blog.viewsCount += 1
    blog.save()
    context = {
        "blog": blog
    }
    return render(request, "blogs/blog.html", context=context)

main/views.py
from django.shortcuts import render
from django.http import request
from django.template import Template
# Create your views here.


def HomePageView(request):
    return render(request, "main/index.html")

projects/views.py
from django.shortcuts import render, get_object_or_404
from django.http import request
from .models import Project, HashtagForProject


def ProjectsView(request):
    projects = Project.objects.order_by("-dateCreated")
    context = {
        "hashtags": HashtagForProject.objects.all(),
        "projects": projects
    }
    return render(request, "projects/projects.html", context=context)


def ProjectsWithHashtagView(request, id):
    hashtag = get_object_or_404(HashtagForProject, pk = id)

    projects = hashtag.projects.order_by("-dateCreated")
    context = {
        "queriedHashtag": hashtag,
        "hashtags": HashtagForProject.objects.all(),
        "projects": projects
    }
    return render(request, "projects/projects.html", context=context)


def ProjectView(request, slug):
    project = get_object_or_404(Project, slug=slug)
    project.viewsCount += 1
    project.save()
    context = {
        "project": project
    }
    return render(request, "projects/project.html", context=context)

blogs/templates/blogs/blog.html
{% extends "base.html" %}
{% load static %}

{% block head-links %}
    <link rel="stylesheet" href="{% static 'blogs/css/blog.css' %}">
{% endblock head-links %}


{% block title %}
    {{ blog.title }}
{% endblock title %}

{% block header %}
Blog
{% endblock header %}

{% block body %}
    <div class = "back-to">
        <i class="fa-solid fa-circle-left"></i><a href="{% url 'blogs:blogs' %}">Back to blogs</a>
    </div>
    <div class="blog">
        <h3 class = "title">{{ blog.title }}</h3>
        <i class="fa-solid fa-pen"></i><span class = "date-created">{{ blog.dateCreated | date:"Y-m-d" }} by Akhliddin</span>
        <i class="fa-solid fa-eye"></i><span class = "views-count">{{ blog.viewsCount }}</span>
        <div class = "content">
            {{ blog.description|safe }}
        </div>
    </div>
{% endblock body %}

blogs/templates/blogs/blogs.html
{% extends "base.html" %}
{% load static %}

{% block head-links %}
    <link rel="stylesheet" href="{% static 'blogs/css/blogs.css' %}">
{% endblock head-links %}


{% block title %}
Blogs
{% endblock title %}

{% block header %}
All blogs
{% endblock header %}

{% block body %}

<section id = "blogs" class="blogs section">
    <h1>All blogs</h1>
    <div class="all-hashtags">
        {% if queriedHashtag %} 
            <div class="hashtag">
                <a href="{% url 'blogs:blogs' %}"><h5 class = "hashtag-content">All</h5></a>
            </div>
        {% else %}
                <div class="hashtag hashtag-selected">
                    <a href="{% url 'blogs:blogs' %}"><h5 class = "hashtag-content">All</h5></a>
                </div>
        {% endif %}
        
        {% for hashtag in hashtags %}
            {% if queriedHashtag and queriedHashtag.content == hashtag.content %} 
                <div class="hashtag hashtag-selected">
                    <a href="{% url 'blogs:blogsWithHashtag' hashtag.pk %}"><h5 class = "hashtag-content">{{ hashtag.content }}</h5></a>
                </div>
            {% else %}
                <div class="hashtag">
                    <a href="{% url 'blogs:blogsWithHashtag' hashtag.pk %}"><h5 class = "hashtag-content">{{ hashtag.content }}</h5></a>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    <div class="blogs-grid">
        {% for blog in blogs %}
            <a href = "{% url 'blogs:blog' blog.slug %}">
                <div class="blog">
                    <img class = "blog-pic" src="{{ blog.imageField.url }}" alt="">
                    <h3>{{ blog.title }}</h3>
                    <div>
                        {{ blog.mini_description|truncatechars:100 }}
                    </div>
                    <div class = "blog-date">
                        <i class="fa-solid fa-pen"></i><p class = "date-created">{{ blog.dateCreated|date:"Y-m-d" }}</p>
                        <i class="fa-solid fa-eye"></i><span class = "views-count">{{ blog.viewsCount }}</span>
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>
</section>
{% endblock body %}

main/templates/main/index.html
{% extends "base.html" %}

{% block title %}
    Backend Developer Portfolio
{% endblock title %}

{% block body %}
    <main>
        <section class="hero">
            <div class="hero-content">
                <h1>Hi, I'm <span class="highlight">Akhliddin</span>, <br>Python Developer</h1>
                <p>Specializing in building scalable, high-performance backend solutions.</p>
                <a href="#about" class="btn">Learn More</a>
            </div>
        </section>

        <section id="about" class="about section">
            <h2>About Me</h2>
            <p>I am a backend developer with experience in building robust backend systems. I am proficient in Python, Django, Django REST framework, FastAPI and databases.</p>
        </section>

        <section id="skills" class="skills section">
            <h2>Skills</h2>
            <div class="skills-grid">
                <div class="skill">
                    <h3>Python</h3>
                    <p>Automation, scripting, and web development.</p>
                </div>
                <div class="skill">
                    <h3>Databases</h3>
                    <p>SQL & NoSQL databases, indexing, and optimization.</p>
                </div>
                <div class="skill">
                    <h3>API Development</h3>
                    <p>Designing and building APIs in DRF and FastAPI.</p>
                </div>
            </div>
        </section>

        <!-- <section id="experience" class="experience section">
            <h2>Experience</h2>
            <div class="experience-grid">
                <div class="experience-item">
                    <h3>Senior Backend Developer - Company A</h3>
                    <p>Worked on high-scale applications with millions of users.</p>
                </div>
                <div class="experience-item">
                    <h3>Backend Developer - Company B</h3>
                    <p>Built microservices architecture for business-critical systems.</p>
                </div>
            </div>
        </section> -->
    </main>
{% endblock body %}

{% block jsLinks %}
    <script src="js/main.js"></script>
{% endblock jsLinks %}

projects/templates/projects/project.html
{% extends "base.html" %}
{% load static %}

{% block head-links %}
    <link rel="stylesheet" href="{% static 'projects/css/project.css' %}">
{% endblock head-links %}


{% block title %}
    {{ project.title }}
{% endblock title %}

{% block header %}
Project
{% endblock header %}

{% block body %}
    <div class = "back-to">
        <i class="fa-solid fa-circle-left"></i><a href="{% url 'projects:projects' %}">Back to projects</a>
    </div>
    <div class="blog">
        <h3 class = "title">{{ project.title }}</h3>
        <i class="fa-solid fa-pen"></i><span class = "date-created">{{ project.dateCreated | date:"Y-m-d" }} by Akhliddin</span>
        <i class="fa-solid fa-eye"></i><span class = "views-count">{{ project.viewsCount }}</span>
        <div class = "content">
            {{ project.description|safe }}
        </div>
    </div>
{% endblock body %}

projects/templates/projects/projects.html
{% extends "base.html" %}
{% load static %}

{% block head-links %}
    <link rel="stylesheet" href="{% static 'projects/css/projects.css' %}">
{% endblock head-links %}


{% block title %}
Projects
{% endblock title %}

{% block header %}
All projects
{% endblock header %}

{% block body %}

<section id = "blogs" class="blogs section">
    <h2>Projects</h2>
    <div class="all-hashtags">
        {% if queriedHashtag %} 
            <div class="hashtag">
                <a href="{% url 'projects:projects' %}"><h3 class = "hashtag-content">All</h3></a>
            </div>
        {% else %}
                <div class="hashtag hashtag-selected">
                    <a href="{% url 'projects:projects' %}"><h3 class = "hashtag-content">All</h3></a>
                </div>
        {% endif %}
        
        {% for hashtag in hashtags %}
            {% if queriedHashtag and queriedHashtag.content == hashtag.content %} 
                <div class="hashtag hashtag-selected">
                    <a href="{% url 'projects:projectsWithHashtag' hashtag.pk %}"><h3 class = "hashtag-content">{{ hashtag.content }}</h3></a>
                </div>
            {% else %}
                <div class="hashtag">
                    <a href="{% url 'projects:projectsWithHashtag' hashtag.pk %}"><h3 class = "hashtag-content">{{ hashtag.content }}</h3></a>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    <div class="blogs-grid">
        {% for project in projects %}
            <a href = "{% url 'projects:project' project.slug %}">
                <div class="blog">
                    <img class = "blog-pic" src="{{ project.imageField.url }}" alt="">
                    <h3>{{ project.title }}</h3>
                    <div>
                        {{ project.mini_description|truncatechars:100 }}
                    </div>
                    <div class = "blog-date">
                        <i class="fa-solid fa-pen"></i><p class = "date-created">{{ project.dateCreated|date:"Y-m-d" }}</p>
                        <i class="fa-solid fa-eye"></i><span class = "views-count">{{ project.viewsCount }}</span>
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>
</section>
{% endblock body %}

templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %} {% endblock title %}</title>
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        {% block extrahead %}
        <script>window.CKEDITOR_BASEPATH = '/my_static/ckeditor/ckeditor/';</script>
        {{ block.super }}
        {% endblock %}
    {% block head-links %}
    {% endblock head-links %}
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <div class="container">
        {% include 'containers/_header.html' %}
        
        {% block body %}
        {% endblock body %}
        
        {% include 'containers/_footer.html' %}
    </div>

    <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    {% block jsLinks %}
    {% endblock jsLinks %}
</body>
</html>

templates/containers/_footer.html
<div class="footer">
    <p>&copy; 2024 Akhliddin - Backend Developer</p>
    <div class="social-links">
        <!-- <a href="https://github.com/your-profile" target="_blank">GitHub</a>
        <a href="https://linkedin.com/in/your-profile" target="_blank">LinkedIn</a>
        <a href="https://linkedin.com/in/your-profile" target="_blank">LeetCode</a> -->
        <a href="https://t.me/ans0220" target = "_blank"><i class="fa-brands fa-telegram"></i></a>
        <a href="https://www.linkedin.com/in/ahliddin-najmiddinov-17796632a/" target = "_blank"><i class="fa-brands fa-linkedin"></i></a>
        <a href="https://github.com/akhliddinnajmiddinov" target = "_blank"><i class="fa-brands fa-github"></i></a>
    </div>
    <p> Phone number +998883707279</p>

</div>

templates/containers/_header.html
<header>
    <nav class="navbar">
        <div class="logo">
            <a href="{% url 'main:main' %}">Akhliddin</a>
        </div>
        <ul class="nav-links">
            <li><a href="{% url 'main:main' %}">Home</a></li>
            <li><a href="{% url 'blogs:blogs' %}">Blogs</a></li>
            <li><a href="{% url 'projects:projects' %}">Projects</a></li>
        </ul>
    </nav>
</header>